### ISSUE TITLE
多数据源字段不统一的解决方案

### ISSUE THREAD

**Issue by 729234500** [dogHere/jdbc-cache#1]
这两天在搞多数据源数据转化迁移的问题。新手，很头疼！对于异构数据源的数据字段标准统一的问题和数据迁移的问题您能否给一些建议

**Comment by dogHere** [comment]
数据迁移的中间可以做一些数据转化。

推荐你用开源的kettle，
1. kettle 在转化中间写js脚本，可以转化字段名，过滤、映射字段，但没办法做reduce。
2. kettle同时支持大部分数据源。

虽然kettle本身难用，考虑到用一次还是可以忍受的。

不建议用本项目，毕竟还不成熟，下一个版本就要把这个版本推倒重写。直到发布1.0版本，才可以被用到生产环境。

@729234500

**Comment by 729234500** [comment]
@dogHere 您好，我想知道kettle如何加载到本地Eclipse啊。而且kettle逻辑太复杂了以至于我根本没有读懂他的代码。所以我想弄一个简单点的

**Comment by dogHere** [comment]
如果是用的话，没必要加载到Eclispse，要调试的话，可以试试mvn。我贴一下我的mvn配置给你：

```xml
    <repositories>

        <repository>
            <id>pentaho-releases</id>
            <url>http://repository.pentaho.org/artifactory/repo/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>pentaho-kettle</groupId>
            <artifactId>kettle-core</artifactId>
            <version>6.1.0.10-320</version>
        </dependency>

        <dependency>
            <groupId>pentaho-kettle</groupId>
            <artifactId>kettle-dbdialog</artifactId>
            <version>6.1.0.10-320</version>
        </dependency>


        <dependency>
            <groupId>pentaho-kettle</groupId>
            <artifactId>kettle-engine</artifactId>
            <version>6.1.0.10-320</version>
        </dependency>
        <dependency>
            <groupId>pentaho-kettle</groupId>
            <artifactId>kettle-ui-swt</artifactId>
            <version>6.1.0.10-320</version>
        </dependency>
    </dependencies>
```

你还需要手动把下载的kettle解包，把其依赖的lib引入到Eclispse。

然后可以这样运行：

```java
//        org.pentaho.di.ui.spoon.Spoon.main(args); //带界面
        org.pentaho.di.kitchen.Kitchen.main(args); //不带界面
```

要注意软件的版本哦，版本不对就运行不起来。

@729234500

**Comment by dogHere** [comment]
kettle本身确实太复杂了。但是要用的话没必要去调试它的代码，实际上这样用就可以了：

```bash
kitchen.sh   -rep=repo文件夹  -job=job名字
```
其中`-rep`和 `-job`可以用界面版自动生成，也可以手动配置，配置文件在`~/.kettle/repositories.xml`.

@729234500

**Comment by 729234500** [comment]
@dogHere okey我试试 我只需要按照你的mvn配置粘贴到我的pom.xml中就可以了么？那您的kettle版本是什么版本啊！
而且他是如何实现异构数据源数据类型统一的呢？

**Comment by dogHere** [comment]
如果利用kettle进行转换数据的话，你【不需要】调试kettle代码。只需了解下：

1.如何写一个kettle的job。这里有一个[例子](http://wiki.pentaho.com/display/EAI/03.+Hello+World+Example)。
2.如何用kettle运行job，上面已经说过了。

至于kettle版本，请在[这里](https://sourceforge.net/projects/pentaho/files/Data%20Integration/)选择6以上的任何一个。

题外话，不要试图得到一个直接的答案，慢慢来。

@729234500

**Comment by 729234500** [comment]
@dogHere  受教了！非常感谢。我试试按照你的方法把kettle项目加载到我的项目上！！！

**Comment by 729234500** [comment]
@dogHere 除了数据转换还有一些其他的东西。我希望我的项目是一个整体。而直接用的话，就把项目分割开。觉得很别扭

**Comment by dogHere** [comment]
1.你可以写一些python脚本或者bash脚本，统一管理项目。
2.你可以调用kettle的api或者类库，集成到自己的项目去(前提很熟悉kettle)。

@729234500
